### ISSUE TITLE
How to specify a default value?

### ISSUE THREAD

**Issue by Telokis** [it-gorillaz/configify#58]
I have my config provider like the following:

```ts
import { Configuration, Value } from "@itgorillaz/configify";

@Configuration()
export class DatabaseConfig {
	@Value("DATABASE_HOST")
	host: string;

	@Value("DATABASE_PORT", {
		parse(value) {
			return parseInt(value);
		},
	})
	port: string;

	@Value("DATABASE_USERNAME")
	username: string;

	@Value("DATABASE_PASSWORD")
	password: string;

	@Value("DATABASE_DATABASE")
	database: string;
}
```

How would I specify default values to be used when the environment variable does not exist or if it's invalid?

**Comment by Telokis** [comment]
The main use-case I have for that is to use configuration as a way to customize sensible defaults.  
For example, if I use a postgres database, the port will most likely be 5432 but maybe someone has something different. I don't want all users to specify their own specific configuration for "obvious" values like that.  
And if I specify defaults for everything, the `.env` becomes optional which is nice for the most basic use-case of my app.

I think specifying the `default` to the `Value` decorator is the best choice.

**Comment by tommelo** [comment]
@Telokis give it a try with the `v1.3.0`
